ALTER TABLE sj_users ADD COLUMN upi_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE sj_users ADD COLUMN qr_code_url VARCHAR(255) DEFAULT NULL;

ALTER TABLE sj_tracking ADD COLUMN page_views INT DEFAULT NULL;
ALTER TABLE sj_tracking ADD COLUMN order_id VARCHAR(64) DEFAULT NULL;
ALTER TABLE sj_tracking ADD COLUMN order_value DECIMAL(18,2) DEFAULT NULL;
ALTER TABLE sj_tracking ADD COLUMN price DECIMAL(18,2) DEFAULT NULL;
ALTER TABLE sj_tracking ADD COLUMN category VARCHAR(100) DEFAULT NULL;
