from datetime import datetime, timezone
from typing import Dict, List, Optional

from sqlalchemy import text

from app.config.database import get_async_session_factory, use_oracle
from app.db.storage_factory import get_storage
from app.utils.logger import logger


class BundleRepository:
    """
    Repository for admin-managed product bundles.
    Bundles group multiple products under a single bundle price.
    Stock is tracked per individual product; pricing is bundle-level.
    """

    def __init__(self):
        self._storage = None
        self._initialized = False

    @property
    def storage(self):
        if self._storage is None:
            self._storage = get_storage("bundles")
        return self._storage

    async def ensure_table_exists(self):
        if self._initialized:
            return
        if not use_oracle():
            self._initialized = True
            return
        from app.config.settings import settings

        suffix = getattr(settings, "table_suffix", "")
        table_name_upper = f"SJ_BUNDLES{suffix}".upper()
        table_name_lower = f"sj_bundles{suffix}".lower()
        constraint_name_lower = f"uq_sj_bundles_external{suffix}".lower()

        factory = get_async_session_factory()
        if not factory:
            return
        async with factory() as session:
            try:
                result = await session.execute(
                    text("SELECT table_name FROM user_tables WHERE table_name = :tname"), {"tname": table_name_upper}
                )
                row = result.fetchone()
                if not row:
                    logger.info("Table %s does not exist. Creating it...", table_name_upper)
                    await session.execute(
                        text(f"""
                        CREATE TABLE {table_name_lower} (
                          id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          external_id  VARCHAR2(32) NOT NULL,
                          doc          CLOB,
                          created_at   TIMESTAMP,
                          updated_at   TIMESTAMP,
                          CONSTRAINT {constraint_name_lower} UNIQUE (external_id)
                        )
                        """)
                    )
                    await session.commit()
                    logger.info("Table %s created successfully.", table_name_upper)
                self._initialized = True
            except Exception as e:
                logger.error("Error ensuring %s exists: %s", table_name_upper, str(e))

    async def findAll(self, query: Optional[Dict] = None) -> List[Dict]:
        await self.ensure_table_exists()
        return await self.storage.findAll(query)

    async def findById(self, id: str) -> Optional[Dict]:
        await self.ensure_table_exists()
        return await self.storage.findById(id)

    async def findOne(self, query: Dict) -> Optional[Dict]:
        await self.ensure_table_exists()
        return await self.storage.findOne(query)

    async def create(self, data: Dict) -> Dict:
        await self.ensure_table_exists()
        data["createdAt"] = datetime.now(timezone.utc).isoformat()
        data["updatedAt"] = datetime.now(timezone.utc).isoformat()
        return await self.storage.create(data)

    async def update(self, id: str, update_data: Dict) -> Optional[Dict]:
        await self.ensure_table_exists()
        update_data["updatedAt"] = datetime.now(timezone.utc).isoformat()
        return await self.storage.update(id, update_data)

    async def delete(self, id: str) -> bool:
        await self.ensure_table_exists()
        return await self.storage.delete(id)

    async def get_active_bundles(self) -> List[Dict]:
        """Return only active (published) bundles."""
        all_bundles = await self.findAll()
        return [b for b in all_bundles if b.get("isActive", True)]

    async def get_bundles_containing_product(self, product_id: str) -> List[Dict]:
        """Return all active bundles that include a given product_id."""
        all_bundles = await self.get_active_bundles()
        result = []
        for bundle in all_bundles:
            items = bundle.get("items", [])
            if any(i.get("productId") == product_id for i in items):
                result.append(bundle)
        return result


bundle_repository = BundleRepository()
