import asyncio
from datetime import datetime
from typing import Dict, List, Optional
from sqlalchemy import text

from app.db.storage_factory import get_storage
from app.config.database import use_db, get_async_session_factory
from app.config.settings import settings
from app.services.email_service import email_service
from app.utils.logger import logger


class ProductNotificationRepository:
    def __init__(self):
        self._storage = None
        self._initialized = False

    @property
    def storage(self):
        if self._storage is None:
            self._storage = get_storage("productNotifications")
        return self._storage

    async def ensure_table_exists(self):
        if self._initialized:
            return
        if not use_db():
            self._initialized = True
            return
        suffix = getattr(settings, "table_suffix", "")
        table_name_upper = f"SJ_PRODUCT_NOTIFICATIONS{suffix}".upper()
        table_name_lower = f"sj_product_notifications{suffix}".lower()
        constraint_name_lower = f"uq_prod_notif_external{suffix}".lower()

        factory = get_async_session_factory()
        if not factory:
            return
        async with factory() as session:
            try:
                result = await session.execute(
                    text("SELECT table_name FROM user_tables WHERE table_name = :tname"), {"tname": table_name_upper}
                )
                row = result.fetchone()
                if not row:
                    logger.info("Table %s does not exist. Creating it...", table_name_upper)
                    await session.execute(
                        text(f"""
                        CREATE TABLE {table_name_lower} (
                          id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          external_id  VARCHAR2(32) NOT NULL,
                          doc          CLOB,
                          created_at   TIMESTAMP,
                          updated_at   TIMESTAMP,
                          CONSTRAINT {constraint_name_lower} UNIQUE (external_id)
                        )
                        """)
                    )
                    await session.commit()
                    logger.info("Table %s created successfully.", table_name_upper)
                self._initialized = True
            except Exception as e:
                logger.error("Error ensuring %s exists: %s", table_name_upper, str(e))

    async def create_notification(self, product_id: str, email: str, user_id: Optional[str] = None) -> Dict:
        await self.ensure_table_exists()
        notification_data = {
            "productId": str(product_id),
            "email": email.strip().lower(),
            "userId": str(user_id) if user_id else None,
            "status": "active",
        }
        # Check if an active notification already exists for this email and product
        existing = await self.storage.findAll(
            {"productId": str(product_id), "email": email.strip().lower(), "status": "active"}
        )
        if existing:
            return existing[0]

        return await self.storage.create(notification_data)

    async def trigger_restock_notifications(self, product_id: str, product_name: str):
        await self.ensure_table_exists()
        active_notifs = await self.storage.findAll({"productId": str(product_id), "status": "active"})
        if not active_notifs:
            return

        domain = "http://localhost:3000"
        origins = settings.allowed_origins_list
        if origins:
            domain = origins[0]

        product_url = f"{domain}/customer/product/{product_id}"
        subject = f"Back in stock: {product_name}"
        clean_product_name = product_name.replace("'", "").replace('"', "")
        plain_text_body = f"Good news! The item {clean_product_name} is back in stock and ready to order. View the product here: {product_url}"
        html_body = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
            <h2 style="color: #ff3f6c;">Good news!</h2>
            <p>The item <strong>{clean_product_name}</strong> is back in stock!</p>
            <p>It is now restocked and ready for you to purchase. Grab yours before it runs out again!</p>
            <div style="margin: 30px 0; text-align: center;">
                <a href="{product_url}" style="display: inline-block; background-color: #ff3f6c; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold;">View Product</a>
            </div>
            <hr style="border: none; border-top: 1px solid #eee;" />
            <p style="font-size: 12px; color: #888;">This is a one-time notification sent because you subscribed to restock alerts for this product at Stationery Junction.</p>
        </div>
        """

        for notif in active_notifs:
            email = notif.get("email")
            if email:
                # Send email
                email_service.send_email(email, subject, plain_text_body, html_body=html_body)
                # Mark as notified
                await self.storage.update(notif["_id"], {"status": "notified"})


product_notification_repository = ProductNotificationRepository()
