import asyncio
from datetime import datetime
from typing import Dict, List, Optional
from sqlalchemy import text

from app.db.storage_factory import get_storage
from app.config.database import use_oracle, get_async_session_factory
from app.utils.logger import logger


class ProductReviewRepository:
    def __init__(self):
        self._storage = None
        self._initialized = False

    @property
    def storage(self):
        if self._storage is None:
            self._storage = get_storage("productReviews")
        return self._storage

    async def ensure_table_exists(self):
        if self._initialized:
            return
        if not use_oracle():
            self._initialized = True
            return
        from app.config.settings import settings

        suffix = getattr(settings, "table_suffix", "")
        table_name_upper = f"SJ_PRODUCT_REVIEWS{suffix}".upper()
        table_name_lower = f"sj_product_reviews{suffix}".lower()
        constraint_name_lower = f"uq_prod_review_external{suffix}".lower()

        factory = get_async_session_factory()
        if not factory:
            return
        async with factory() as session:
            try:
                result = await session.execute(
                    text("SELECT table_name FROM user_tables WHERE table_name = :tname"), {"tname": table_name_upper}
                )
                row = result.fetchone()
                if not row:
                    logger.info("Table %s does not exist. Creating it...", table_name_upper)
                    await session.execute(
                        text(f"""
                        CREATE TABLE {table_name_lower} (
                          id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          external_id  VARCHAR2(32) NOT NULL,
                          doc          CLOB,
                          created_at   TIMESTAMP,
                          updated_at   TIMESTAMP,
                          CONSTRAINT {constraint_name_lower} UNIQUE (external_id)
                        )
                        """)
                    )
                    await session.commit()
                    logger.info("Table %s created successfully.", table_name_upper)
                self._initialized = True
            except Exception as e:
                logger.error("Error ensuring %s exists: %s", table_name_upper, str(e))

    async def findAll(self, query: Optional[Dict] = None) -> List[Dict]:
        await self.ensure_table_exists()
        return await self.storage.findAll(query)

    async def findById(self, id: str) -> Optional[Dict]:
        await self.ensure_table_exists()
        return await self.storage.findById(id)

    async def create(self, data: Dict) -> Dict:
        await self.ensure_table_exists()
        return await self.storage.create(data)

    async def update(self, id: str, update_data: Dict) -> Optional[Dict]:
        await self.ensure_table_exists()
        return await self.storage.update(id, update_data)

    async def delete(self, id: str) -> bool:
        await self.ensure_table_exists()
        return await self.storage.delete(id)


product_review_repository = ProductReviewRepository()
