import asyncio
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional
from app.models.schemas import ClassificationTagResponse
from sqlalchemy import text

from app.db.storage_factory import get_storage
from app.config.database import use_oracle, is_oracle, get_async_session_factory
from app.utils.logger import logger

if TYPE_CHECKING:
    from app.models.daos import ClassificationTagsInternalCreate, ClassificationTagsInternalUpdate
    


class ReviewClassificationRepository:
    def __init__(self):
        self._storage = None
        self._initialized = False

    @property
    def storage(self):
        if self._storage is None:
            self._storage = get_storage("classificationTags")
        return self._storage

    async def ensure_table_exists(self):
        if self._initialized:
            return
        if not use_oracle() or not is_oracle():
            self._initialized = True
            await self._prepopulate_defaults()
            return
        from app.config.settings import settings

        table_name_upper = f"SJ_CLASSIFICATION_TAGS".upper()
        table_name_lower = f"sj_classification_tags".lower()
        constraint_name_lower = f"uq_class_tags_external".lower()

        factory = get_async_session_factory()
        if not factory:
            return
        async with factory() as session:
            try:
                result = await session.execute(
                    text("SELECT table_name FROM user_tables WHERE table_name = :tname"), {"tname": table_name_upper}
                )
                row = result.fetchone()
                if not row:
                    logger.info("Table %s does not exist. Creating it...", table_name_upper)
                    await session.execute(
                        text(f"""
                        CREATE TABLE {table_name_lower} (
                          id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          external_id  VARCHAR2(32) NOT NULL,
                          doc          CLOB,
                          created_at   TIMESTAMP,
                          updated_at   TIMESTAMP,
                          CONSTRAINT {constraint_name_lower} UNIQUE (external_id)
                        )
                        """)
                    )
                    await session.commit()
                    logger.info("Table %s created successfully.", table_name_upper)
                self._initialized = True
                await self._prepopulate_defaults()
            except Exception as e:
                logger.error("Error ensuring %s exists: %s", table_name_upper, str(e))

    async def _prepopulate_defaults(self):
        try:
            all_classes = await self.storage.findAll()
            if not all_classes:
                defaults = ["Quality", "Price", "Delivery", "Other"]
                for name in defaults:
                    await self.storage.create({"name": name, "isActive": True})
                logger.info("Pre-populated default review classifications: %s", defaults)
        except Exception as e:
            logger.error("Failed to pre-populate default classifications: %s", str(e))

    async def findAll(self, query: Optional[dict] = None) -> List[ClassificationTagResponse]:
        await self.ensure_table_exists()
        return await self.storage.findAll(query)

    async def findById(self, id: str) -> Optional[ClassificationTagResponse]:
        await self.ensure_table_exists()
        return await self.storage.findById(id)

    async def create(self, data: 'ClassificationTagsInternalCreate') -> ClassificationTagResponse:
        await self.ensure_table_exists()
        return await self.storage.create(data)

    async def update(self, id: str, update_data: 'ClassificationTagsInternalUpdate') -> Optional[ClassificationTagResponse]:
        await self.ensure_table_exists()
        return await self.storage.update(id, update_data)

    async def delete(self, id: str) -> bool:
        await self.ensure_table_exists()
        return await self.storage.delete(id)


review_classification_repository = ReviewClassificationRepository()
