import asyncio
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional
from sqlalchemy import text

from app.db.storage_factory import get_storage
from app.config.database import use_oracle, get_async_session_factory
from app.utils.logger import logger


class StockReservationRepository:
    def __init__(self):
        # We wrap storage retrieval in a property or get it dynamically
        self._storage = None
        self._initialized = False

    @property
    def storage(self):
        if self._storage is None:
            self._storage = get_storage("stockReservations")
        return self._storage

    async def ensure_table_exists(self):
        if self._initialized:
            return
        if not use_oracle():
            self._initialized = True
            return
        from app.config.settings import settings
        suffix = getattr(settings, "table_suffix", "")
        table_name_upper = f"SJ_STOCK_RESERVATIONS{suffix}".upper()
        table_name_lower = f"sj_stock_reservations{suffix}".lower()
        constraint_name_lower = f"uq_stock_res_external{suffix}".lower()

        factory = get_async_session_factory()
        if not factory:
            return
        async with factory() as session:
            try:
                # Check if table exists (Oracle user_tables names are upper case)
                result = await session.execute(
                    text("SELECT table_name FROM user_tables WHERE table_name = :tname"),
                    {"tname": table_name_upper}
                )
                row = result.fetchone()
                if not row:
                    logger.info("Table %s does not exist. Creating it...", table_name_upper)
                    await session.execute(
                        text(f"""
                        CREATE TABLE {table_name_lower} (
                          id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          external_id  VARCHAR2(32) NOT NULL,
                          doc          CLOB,
                          created_at   TIMESTAMP,
                          updated_at   TIMESTAMP,
                          CONSTRAINT {constraint_name_lower} UNIQUE (external_id)
                        )
                        """)
                    )
                    await session.commit()
                    logger.info("Table %s created successfully.", table_name_upper)
                self._initialized = True
            except Exception as e:
                logger.error("Error ensuring %s exists: %s", table_name_upper, str(e))

    def _parse_date(self, date_str: str) -> datetime:
        if not date_str:
            return datetime.now(timezone.utc)
        try:
            clean_str = date_str.replace("Z", "+00:00")
            dt = datetime.fromisoformat(clean_str)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt
        except Exception:
            return datetime.now(timezone.utc)

    def _now_iso(self) -> str:
        return datetime.now(timezone.utc).isoformat() + "Z"

    async def get_reserved_quantity(self, product_id: str, exclude_user_id: Optional[str] = None) -> int:
        """Returns the total active, non-expired reserved quantity for a product."""
        await self.ensure_table_exists()
        # Find all active reservations
        all_res = await self.storage.findAll({"productId": str(product_id), "status": "active"})
        
        total = 0
        now = datetime.now(timezone.utc)
        
        for res in all_res:
            if exclude_user_id and str(res.get("userId")) == str(exclude_user_id):
                continue
            
            # Check expiry
            expires_at = self._parse_date(res.get("expiresAt"))
            if expires_at > now:
                total += int(res.get("quantity", 0))
                
        return total

    async def get_user_reservations(self, user_id: str) -> List[Dict]:
        """Returns all active, non-expired reservations for a user."""
        await self.ensure_table_exists()
        all_res = await self.storage.findAll({"userId": str(user_id), "status": "active"})
        
        active_res = []
        now = datetime.now(timezone.utc)
        
        for res in all_res:
            expires_at = self._parse_date(res.get("expiresAt"))
            if expires_at > now:
                active_res.append(res)
                
        return active_res

    async def reserve_stock(self, product_id: str, user_id: str, quantity: int, ttl_minutes: int) -> Dict:
        """Creates or updates a reservation for a product and user."""
        await self.ensure_table_exists()
        
        now = datetime.now(timezone.utc)
        expires_at = now + timedelta(minutes=ttl_minutes)
        
        # Release any existing active reservation of this user for this product first
        await self.release_user_reservations(user_id, product_id)
        
        reservation_data = {
            "productId": str(product_id),
            "userId": str(user_id),
            "quantity": int(quantity),
            "status": "active",
            "expiresAt": expires_at.isoformat() + "Z",
        }
        
        created = await self.storage.create(reservation_data)
        logger.info(
            "Created stock reservation for user %s, product %s, qty %d (expires in %d min)",
            user_id, product_id, quantity, ttl_minutes
        )
        return created

    async def release_user_reservations(self, user_id: str, product_id: Optional[str] = None):
        """Marks active reservations for a user as released."""
        await self.ensure_table_exists()
        query = {"userId": str(user_id), "status": "active"}
        if product_id:
            query["productId"] = str(product_id)
            
        active_res = await self.storage.findAll(query)
        for res in active_res:
            await self.storage.update(res["_id"], {"status": "released"})
            logger.info("Released stock reservation %s for user %s", res["_id"], user_id)

    async def fulfill_user_reservations(self, user_id: str, product_id: Optional[str] = None):
        """Marks active reservations for a user as fulfilled (order placed)."""
        await self.ensure_table_exists()
        query = {"userId": str(user_id), "status": "active"}
        if product_id:
            query["productId"] = str(product_id)
            
        active_res = await self.storage.findAll(query)
        now = datetime.now(timezone.utc)
        
        for res in active_res:
            expires_at = self._parse_date(res.get("expiresAt"))
            # Only fulfill if not already expired
            if expires_at > now:
                await self.storage.update(res["_id"], {"status": "fulfilled"})
                logger.info("Fulfilled stock reservation %s for user %s", res["_id"], user_id)
            else:
                await self.storage.update(res["_id"], {"status": "expired"})

    async def cleanup_expired(self):
        """Finds and marks all expired reservations as 'expired'."""
        await self.ensure_table_exists()
        active_res = await self.storage.findAll({"status": "active"})
        
        now = datetime.now(timezone.utc)
        expired_count = 0
        
        for res in active_res:
            expires_at = self._parse_date(res.get("expiresAt"))
            if expires_at <= now:
                await self.storage.update(res["_id"], {"status": "expired"})
                expired_count += 1
                
        if expired_count > 0:
            logger.info("Cleaned up %d expired stock reservations", expired_count)


# Global singleton instance
stock_reservation_repository = StockReservationRepository()
