from datetime import datetime
from typing import Optional, List, Any, Dict
from pydantic import Field
from app.models.core import DictCompatibleModel

class Ad(DictCompatibleModel):
    id: str = Field(default=None, alias='_id')
    external_id: Optional[Any] = Field(default=None, alias='external_id')
    name: Optional[Any] = Field(default=None, alias='name')
    platform: Optional[Any] = Field(default=None, alias='platform')
    objective: Optional[Any] = Field(default=None, alias='objective')
    status: Optional[Any] = Field(default=None, alias='status')
    budget_daily: Optional[Any] = Field(default=None, alias='budget_daily')
    budget_total: Optional[Any] = Field(default=None, alias='budget_total')
    currency: Optional[Any] = Field(default=None, alias='currency')
    start_date: Optional[Any] = Field(default=None, alias='start_date')
    end_date: Optional[Any] = Field(default=None, alias='end_date')
    target_url: Optional[Any] = Field(default=None, alias='target_url')
    headline: Optional[Any] = Field(default=None, alias='headline')
    description: Optional[Any] = Field(default=None, alias='description')
    image_url: Optional[Any] = Field(default=None, alias='image_url')
    google_campaign_id: Optional[Any] = Field(default=None, alias='google_campaign_id')
    google_ad_group_id: Optional[Any] = Field(default=None, alias='google_ad_group_id')
    meta_campaign_id: Optional[Any] = Field(default=None, alias='meta_campaign_id')
    meta_ad_set_id: Optional[Any] = Field(default=None, alias='meta_ad_set_id')
    utm_source: Optional[Any] = Field(default=None, alias='utm_source')
    utm_medium: Optional[Any] = Field(default=None, alias='utm_medium')
    utm_campaign: Optional[Any] = Field(default=None, alias='utm_campaign')
    google_conversion_id: Optional[Any] = Field(default=None, alias='google_conversion_id')
    google_conversion_label: Optional[Any] = Field(default=None, alias='google_conversion_label')
    meta_pixel_id: Optional[Any] = Field(default=None, alias='meta_pixel_id')
    notes: Optional[Any] = Field(default=None, alias='notes')
    stats: Optional[Any] = Field(default=None, alias='stats')
    impressions: Optional[Any] = Field(default=None, alias='impressions')
    clicks: Optional[Any] = Field(default=None, alias='clicks')
    leads: Optional[Any] = Field(default=None, alias='leads')
    purchases: Optional[Any] = Field(default=None, alias='purchases')
    add_to_cart: Optional[Any] = Field(default=None, alias='add_to_cart')
    conversions: Optional[Any] = Field(default=None, alias='conversions')
    conversion_value: Optional[Any] = Field(default=None, alias='conversion_value')
    ctr: Optional[Any] = Field(default=None, alias='ctr')
    cvr: Optional[Any] = Field(default=None, alias='cvr')
    created_at: Optional[datetime] = Field(default=None, alias='createdAt')
    updated_at: Optional[datetime] = Field(default=None, alias='updatedAt')
    launched_at: Optional[datetime] = Field(default=None, alias='launchedAt')
    eid: Optional[Any] = Field(default=None, alias='eid')
    c: Optional[Any] = Field(default=None, alias='c')
    u: Optional[Any] = Field(default=None, alias='u')
