from datetime import datetime
from typing import Optional, List, Any, Dict
from pydantic import Field
from app.models.core import DictCompatibleModel

class DynamicRelational(DictCompatibleModel):
    id: str = Field(default=None, alias='_id')
    external_id: Optional[Any] = Field(default=None, alias='externalId')
    pid: Optional[Any] = Field(default=None, alias='pid')
    val: Optional[Any] = Field(default=None, alias='val')
    k: Optional[Any] = Field(default=None, alias='k')
    v: Optional[Any] = Field(default=None, alias='v')
    eid: Optional[Any] = Field(default=None, alias='eid')
    c: Optional[Any] = Field(default=None, alias='c')
    u: Optional[Any] = Field(default=None, alias='u')
    sj_coupons: Optional[Any] = Field(default=None, alias='sj_coupons')
    api_name: Optional[Any] = Field(default=None, alias='api_name')
    child_tables: Optional[Any] = Field(default=None, alias='child_tables')
    quantity_tiers: Optional[Any] = Field(default=None, alias='quantityTiers')
    applicable_roles: Optional[Any] = Field(default=None, alias='applicableRoles')
    applicable_user_ids: Optional[Any] = Field(default=None, alias='applicableUserIds')
    applicable_categories: Optional[Any] = Field(default=None, alias='applicableCategories')
    applies_to_value_ids: Optional[Any] = Field(default=None, alias='appliesToValueIds')
    excluded_product_ids: Optional[Any] = Field(default=None, alias='excludedProductIds')
    sj_activities: Optional[Any] = Field(default=None, alias='sj_activities')
    meta: Optional[Any] = Field(default=None, alias='meta')
    sj_notifications: Optional[Any] = Field(default=None, alias='sj_notifications')
    data: Optional[Any] = Field(default=None, alias='data')
    sj_return_requests: Optional[Any] = Field(default=None, alias='sj_return_requests')
    items: Optional[Any] = Field(default=None, alias='items')
    valet_decline_history: Optional[Any] = Field(default=None, alias='valetDeclineHistory')
    sj_schemes: Optional[Any] = Field(default=None, alias='sj_schemes')
    sj_contacts: Optional[Any] = Field(default=None, alias='sj_contacts')
    addresses: Optional[Any] = Field(default=None, alias='addresses')
    phone_numbers: Optional[Any] = Field(default=None, alias='phoneNumbers')
    sj_support_tickets: Optional[Any] = Field(default=None, alias='sj_support_tickets')
    attachments: Optional[Any] = Field(default=None, alias='attachments')
    responses: Optional[Any] = Field(default=None, alias='responses')
    sj_device_subscriptions: Optional[Any] = Field(default=None, alias='sj_device_subscriptions')
    keys: Optional[Any] = Field(default=None, alias='keys')
    subscription: Optional[Any] = Field(default=None, alias='subscription')
    sj_collections: Optional[Any] = Field(default=None, alias='sj_collections')
    visible_pages: Optional[Any] = Field(default=None, alias='visiblePages')
    user_segments: Optional[Any] = Field(default=None, alias='userSegments')
    visibility_rules: Optional[Any] = Field(default=None, alias='visibilityRules')
    product_ids: Optional[Any] = Field(default=None, alias='productIds')
    sj_search_tags: Optional[Any] = Field(default=None, alias='sj_search_tags')
    categories: Optional[Any] = Field(default=None, alias='categories')
    sub_categories: Optional[Any] = Field(default=None, alias='subCategories')
    brands: Optional[Any] = Field(default=None, alias='brands')
    collections: Optional[Any] = Field(default=None, alias='collections')
    sj_delivery_charges: Optional[Any] = Field(default=None, alias='sj_delivery_charges')
    tiers: Optional[Any] = Field(default=None, alias='tiers')
    sj_delivery_charge_defaults: Optional[Any] = Field(default=None, alias='sj_delivery_charge_defaults')
    sj_delivery_slots: Optional[Any] = Field(default=None, alias='sj_delivery_slots')
    slots: Optional[Any] = Field(default=None, alias='slots')
    sj_delivery_zones: Optional[Any] = Field(default=None, alias='sj_delivery_zones')
    pincodes: Optional[Any] = Field(default=None, alias='pincodes')
    sj_events: Optional[Any] = Field(default=None, alias='sj_events')
    payload: Optional[Any] = Field(default=None, alias='payload')
