from datetime import datetime
from typing import Optional, List, Any, Dict
from pydantic import Field
from app.models.core import DictCompatibleModel

class SubOrder(DictCompatibleModel):
    id: str = Field(default=None, alias='_id')
    config_id: Optional[Any] = Field(default=None, alias='configId')
    slot_id: Optional[Any] = Field(default=None, alias='slotId')
    date: Optional[Any] = Field(default=None, alias='date')
    discount_type: Optional[Any] = Field(default=None, alias='discountType')
    discount_value: Optional[Any] = Field(default=None, alias='discountValue')
    name: Optional[Any] = Field(default=None, alias='name')
    phone: Optional[Any] = Field(default=None, alias='phone')
    line1: Optional[Any] = Field(default=None, alias='line1')
    city: Optional[Any] = Field(default=None, alias='city')
    state: Optional[Any] = Field(default=None, alias='state')
    pincode: Optional[Any] = Field(default=None, alias='pincode')
    product_id: Optional[Any] = Field(default=None, alias='productId')
    qty: Optional[Any] = Field(default=None, alias='qty')
    price: Optional[Any] = Field(default=None, alias='price')
    parent_order_id: Optional[Any] = Field(default=None, alias='parentOrderId')
    external_id: Optional[Any] = Field(default=None, alias='external_id')
    sub_order_number: Optional[Any] = Field(default=None, alias='sub_order_number')
    parent_order_number: Optional[Any] = Field(default=None, alias='parent_order_number')
    seller_id: Optional[Any] = Field(default=None, alias='seller_id')
    seller_name: Optional[Any] = Field(default=None, alias='seller_name')
    user_id: Optional[Any] = Field(default=None, alias='user_id')
    subtotal: Optional[Any] = Field(default=None, alias='subtotal')
    tax: Optional[Any] = Field(default=None, alias='tax')
    shipping: Optional[Any] = Field(default=None, alias='shipping')
    delivery_gst: Optional[Any] = Field(default=None, alias='delivery_gst')
    discount: Optional[Any] = Field(default=None, alias='discount')
    total: Optional[Any] = Field(default=None, alias='total')
    order_type: Optional[Any] = Field(default=None, alias='order_type')
    status: Optional[Any] = Field(default=None, alias='status')
    payment_method: Optional[Any] = Field(default=None, alias='payment_method')
    payment_status: Optional[Any] = Field(default=None, alias='payment_status')
    is_urgent_delivery: bool = Field(default=None, alias='is_urgent_delivery')
    delivery_slot_config_id: Optional[Any] = Field(default=None, alias='delivery_slot_config_id')
    delivery_slot_id: Optional[Any] = Field(default=None, alias='delivery_slot_id')
    delivery_slot_date: Optional[Any] = Field(default=None, alias='delivery_slot_date')
    notes: Optional[Any] = Field(default=None, alias='notes')
    coupon_code: Optional[Any] = Field(default=None, alias='coupon_code')
    coupon_info_type: Optional[Any] = Field(default=None, alias='coupon_info_type')
    coupon_info_value: Optional[Any] = Field(default=None, alias='coupon_info_value')
    commission_status: Optional[Any] = Field(default=None, alias='commission_status')
    shipping_name: Optional[Any] = Field(default=None, alias='shipping_name')
    shipping_phone: Optional[Any] = Field(default=None, alias='shipping_phone')
    shipping_line1: Optional[Any] = Field(default=None, alias='shipping_line1')
    shipping_city: Optional[Any] = Field(default=None, alias='shipping_city')
    shipping_state: Optional[Any] = Field(default=None, alias='shipping_state')
    shipping_pincode: Optional[Any] = Field(default=None, alias='shipping_pincode')
    billing_name: Optional[Any] = Field(default=None, alias='billing_name')
    billing_phone: Optional[Any] = Field(default=None, alias='billing_phone')
    billing_line1: Optional[Any] = Field(default=None, alias='billing_line1')
    billing_city: Optional[Any] = Field(default=None, alias='billing_city')
    billing_state: Optional[Any] = Field(default=None, alias='billing_state')
    billing_pincode: Optional[Any] = Field(default=None, alias='billing_pincode')
    pickup_status: Optional[Any] = Field(default=None, alias='pickup_status')
    assigned_valet: Optional[Any] = Field(default=None, alias='assigned_valet')
    created_at: Optional[Any] = Field(default=None, alias='created_at')
    updated_at: Optional[Any] = Field(default=None, alias='updated_at')
    sub_order_id: Optional[Any] = Field(default=None, alias='sub_order_id')
    row_id: Optional[Any] = Field(default=None, alias='row_id')
