import asyncio
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Add backend root so app imports work
backend_root = Path(__file__).resolve().parent
sys.path.insert(0, str(backend_root))

load_dotenv()

from sqlalchemy import text
from app.config.database import get_async_session_factory

async def main():
    factory = get_async_session_factory()
    if not factory:
        print("No database connection factory. Check .env")
        return

    create_table_sql = """
    CREATE TABLE sj_referral_settings (
      id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      external_id    VARCHAR2(32) NOT NULL,
      segment        VARCHAR2(32) NOT NULL,
      discount_type  VARCHAR2(32),
      discount_value NUMBER(18,2) DEFAULT 0,
      is_active      NUMBER(1) DEFAULT 0,
      created_at     TIMESTAMP,
      updated_at     TIMESTAMP,
      CONSTRAINT uq_sj_referral_settings_external UNIQUE (external_id),
      CONSTRAINT uq_sj_referral_settings_segment UNIQUE (segment)
    )
    """

    print("Connecting to Oracle database...")
    async with factory() as session:
        try:
            print("Creating table sj_referral_settings...")
            await session.execute(text(create_table_sql))
            await session.commit()
            print("Successfully created sj_referral_settings table and index.")
        except Exception as e:
            print(f"Error creating table/index: {e}")
            await session.rollback()

if __name__ == "__main__":
    asyncio.run(main())
