import asyncio
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

backend_root = Path(__file__).resolve().parent
sys.path.insert(0, str(backend_root))

load_dotenv()

from app.config.database import get_async_session_factory
from sqlalchemy import text


async def main():
    fac = get_async_session_factory()
    async with fac() as s:
        print("Syncing identity column USER_ID sequence with table max value...")
        sql = "ALTER TABLE sj_users MODIFY (USER_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))"
        try:
            await s.execute(text(sql))
            await s.commit()
            print("Successfully synced identity sequence.")
        except Exception as e:
            print("Error syncing sequence:", e)


if __name__ == "__main__":
    asyncio.run(main())
