"""Apply the email verification tables and columns migration to Oracle DB."""

import asyncio
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

backend_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(backend_root))
os.chdir(backend_root)

load_dotenv()

from sqlalchemy import text
from app.config.database import get_async_session_factory

STATEMENTS = [
    # 1. Add is_email_verified column to sj_users
    """ALTER TABLE sj_users ADD is_email_verified NUMBER DEFAULT 0 NOT NULL""",
    
    # 2. Create sj_email_otps table
    """CREATE TABLE sj_email_otps (
        id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        email        VARCHAR2(255) NOT NULL,
        device_key   VARCHAR2(128) DEFAULT 'default' NOT NULL,
        otp_code     VARCHAR2(10) NOT NULL,
        verify_attempts NUMBER DEFAULT 0,
        created_at   TIMESTAMP NOT NULL,
        expires_at   TIMESTAMP NOT NULL,
        last_sent_at TIMESTAMP NOT NULL
    )""",
    "CREATE INDEX ix_sj_email_otps_email ON sj_email_otps (email)",
    "CREATE INDEX ix_sj_email_otps_expires ON sj_email_otps (expires_at)",
    "CREATE INDEX ix_sj_email_otps_em_dev ON sj_email_otps (email, device_key)",
    
    # 3. Create sj_email_otp_send_log table for rate limiting
    """CREATE TABLE sj_email_otp_send_log (
        id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        email        VARCHAR2(255) NOT NULL,
        sent_at      TIMESTAMP NOT NULL
    )""",
    "CREATE INDEX ix_sj_em_otp_log_email ON sj_email_otp_send_log (email)",
    "CREATE INDEX ix_sj_em_otp_log_sent ON sj_email_otp_send_log (sent_at)",
]


async def apply_migration():
    factory = get_async_session_factory()
    if not factory:
        print("No factory created. Check DATABASE_URL in .env.")
        return

    async with factory() as session:
        for stmt in STATEMENTS:
            label = stmt.strip()[:80]
            print(f"Executing: {label}...")
            try:
                await session.execute(text(stmt))
                print("  OK")
            except Exception as e:
                err_str = str(e)
                if "ORA-01430" in err_str:  # column being added already exists in table
                    print("  Column is_email_verified already exists, skipping.")
                elif "ORA-00955" in err_str:  # name is already used by an existing object
                    print("  Table or index already exists, skipping.")
                else:
                    print(f"  Error: {e}")
        await session.commit()
    print("Email verification migration complete.")


if __name__ == "__main__":
    asyncio.run(apply_migration())
