"""Apply the OTP tables migration to Oracle DB."""

import asyncio
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

backend_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(backend_root))
os.chdir(backend_root)

load_dotenv()

from sqlalchemy import text
from app.config.database import get_async_session_factory

STATEMENTS = [
    """CREATE TABLE sj_otps (
        id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        phone        VARCHAR2(20) NOT NULL,
        device_key   VARCHAR2(128) DEFAULT 'default' NOT NULL,
        otp_code     VARCHAR2(10) NOT NULL,
        verify_attempts NUMBER DEFAULT 0,
        created_at   TIMESTAMP NOT NULL,
        expires_at   TIMESTAMP NOT NULL,
        last_sent_at TIMESTAMP NOT NULL
    )""",
    "CREATE INDEX ix_sj_otps_phone ON sj_otps (phone)",
    "CREATE INDEX ix_sj_otps_expires ON sj_otps (expires_at)",
    "CREATE INDEX ix_sj_otps_phone_device ON sj_otps (phone, device_key)",
    """CREATE TABLE sj_otp_send_log (
        id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        phone        VARCHAR2(20) NOT NULL,
        sent_at      TIMESTAMP NOT NULL
    )""",
    "CREATE INDEX ix_sj_otp_send_log_phone ON sj_otp_send_log (phone)",
    "CREATE INDEX ix_sj_otp_send_log_sent ON sj_otp_send_log (sent_at)",
]


async def apply_migration():
    factory = get_async_session_factory()
    if not factory:
        print("No factory created. Check DATABASE_URL in .env.")
        return

    async with factory() as session:
        for stmt in STATEMENTS:
            label = stmt.strip()[:80]
            print(f"Executing: {label}...")
            try:
                await session.execute(text(stmt))
                print("  OK")
            except Exception as e:
                if "ORA-00955" in str(e):
                    print("  Already exists, skipping.")
                else:
                    print(f"  Error: {e}")
        await session.commit()
    print("OTP migration complete.")


if __name__ == "__main__":
    asyncio.run(apply_migration())
