CREATE TABLE sj_delivery_slots (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  segment      VARCHAR2(64),
  "DATE"       VARCHAR2(32),
  is_active    NUMBER(1) DEFAULT 1,
  slots        CLOB,
  pincodes     CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_delivery_slots_external UNIQUE (external_id)
);

CREATE INDEX ix_sj_delivery_slots_date ON sj_delivery_slots ("DATE");

CREATE INDEX ix_sj_delivery_slots_segment ON sj_delivery_slots (segment);
