#!/usr/bin/env python3
"""
One-off migration: read app/data/*.json and insert into Oracle.
Run after schema_oracle.sql has been applied. Uses DATABASE_URL.
Collections with full DAOs (e.g. users) are migrated with column mapping;
document-style tables get the full JSON in the doc column.
"""

import asyncio
import json
import os
import sys
from pathlib import Path
from datetime import datetime

# Add backend root so app imports work
backend_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(backend_root))
os.chdir(backend_root)

from dotenv import load_dotenv

load_dotenv()

# Must set DATABASE_URL
if not os.environ.get("DATABASE_URL"):
    print("Set DATABASE_URL in .env and run again.")
    sys.exit(1)


async def load_json(collection: str) -> list:
    path = backend_root / "app" / "data" / f"{collection}.json"
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    try:
        return json.loads(text or "[]")
    except json.JSONDecodeError:
        return []


async def migrate_users():
    """Migrate users into sj_users with column mapping."""
    from sqlalchemy import text
    from app.config.database import get_async_session_factory

    factory = get_async_session_factory()
    if not factory:
        return 0
    docs = await load_json("users")
    if not docs:
        return 0
    count = 0
    for doc in docs:
        external_id = doc.get("_id")
        if not external_id:
            continue
        user_id = doc.get("userId")
        user_id_formatted = doc.get("userIdFormatted") or (f"USER-{user_id}" if user_id else None)
        address = doc.get("address")
        saved = doc.get("savedAddresses", [])
        address_json = json.dumps(address, default=str) if address else None
        saved_json = json.dumps(saved, default=str) if saved else None
        created = doc.get("createdAt")
        updated = doc.get("updatedAt")
        try:
            created_ts = datetime.fromisoformat(created.replace("Z", "+00:00")) if created else datetime.utcnow()
            updated_ts = datetime.fromisoformat(updated.replace("Z", "+00:00")) if updated else datetime.utcnow()
        except Exception:
            created_ts = updated_ts = datetime.utcnow()
        async with factory() as session:
            await session.execute(
                text("""
                    INSERT INTO sj_users (
                        external_id, user_id, user_id_formatted, name, email, password_hash,
                        role, phone, company_name, address, saved_addresses, is_active,
                        approval_status, is_deactivated, credit_limit, credit_used, payment_terms,
                        assigned_salesperson, created_at, updated_at
                    ) VALUES (
                        :eid, :uid, :uid_fmt, :name, :email, :pwd, :role, :phone, :company,
                        :address, :saved, :is_active, :approval, :deact, :climit, :cused,
                        :terms, :salesperson, :created, :updated
                    )
                """),
                {
                    "eid": external_id,
                    "uid": user_id,
                    "uid_fmt": user_id_formatted,
                    "name": doc.get("name"),
                    "email": doc.get("email"),
                    "pwd": doc.get("password"),
                    "role": doc.get("role"),
                    "phone": doc.get("phone") or None,
                    "company": doc.get("companyName"),
                    "address": address_json,
                    "saved": saved_json,
                    "is_active": 1 if doc.get("isActive", True) else 0,
                    "approval": doc.get("approvalStatus"),
                    "deact": 1 if doc.get("isDeactivated") else 0,
                    "climit": doc.get("creditLimit", 0),
                    "cused": doc.get("creditUsed", 0),
                    "terms": str(doc.get("paymentTerms", "30")).replace("net_", ""),
                    "salesperson": doc.get("assignedSalesperson") or doc.get("assignedRetailer"),
                    "created": created_ts,
                    "updated": updated_ts,
                },
            )
            await session.commit()
            count += 1
    # Sync sequence
    from sqlalchemy import text

    async with factory() as session:
        try:
            await session.execute(
                text("ALTER TABLE sj_users MODIFY (USER_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))")
            )
            await session.commit()
            print("  Successfully synced USER_ID identity sequence after user migration.")
        except Exception as e:
            print(f"  Warning: failed to sync USER_ID sequence: {e}")
            await session.rollback()
    return count


async def migrate_doc_table(collection: str, table_name: str) -> int:
    """Migrate a document-style collection into a table with (external_id, doc, created_at, updated_at)."""
    from sqlalchemy import text
    from app.config.database import get_async_session_factory

    factory = get_async_session_factory()
    if not factory:
        return 0
    docs = await load_json(collection)
    if not docs:
        return 0
    count = 0
    for doc in docs:
        external_id = doc.get("_id") or doc.get("id")
        if not external_id:
            external_id = str(doc.get("_id", ""))
        if not external_id:
            continue
        payload = {k: v for k, v in doc.items() if k not in ("_id", "id")}
        doc_json = json.dumps(payload, default=str)
        created = doc.get("createdAt") or doc.get("created_at")
        updated = doc.get("updatedAt") or doc.get("updated_at")
        try:
            created_ts = datetime.fromisoformat(created.replace("Z", "+00:00")) if created else datetime.utcnow()
            updated_ts = datetime.fromisoformat(updated.replace("Z", "+00:00")) if updated else datetime.utcnow()
        except Exception:
            created_ts = updated_ts = datetime.utcnow()
        async with factory() as session:
            try:
                await session.execute(
                    text(f"""
                        INSERT INTO {table_name} (external_id, doc, created_at, updated_at)
                        VALUES (:eid, :doc, :created, :updated)
                    """),
                    {"eid": str(external_id), "doc": doc_json, "created": created_ts, "updated": updated_ts},
                )
                await session.commit()
                count += 1
            except Exception as e:
                await session.rollback()
                print(f"  Skip {collection} doc {external_id}: {e}")
    return count


DOC_COLLECTIONS = [
    ("activities", "sj_activities"),
    ("categoryTags", "sj_category_tags"),
    ("collections", "sj_collections"),
    ("contacts", "sj_contacts"),
    ("deliveryCharges", "sj_delivery_charges"),
    ("deliveryChargeDefaults", "sj_delivery_charge_defaults"),
    ("deviceSubscriptions", "sj_device_subscriptions"),
    ("events", "sj_events"),
    ("notifications", "sj_notifications"),
    ("orderFeedback", "sj_order_feedback"),
    ("payments", "sj_payments"),
    ("promoStrips", "sj_promo_strips"),
    ("pushNotifications", "sj_push_notifications"),
    ("savedForLater", "sj_saved_for_later"),
    ("searchTags", "sj_search_tags"),
    ("supportTickets", "sj_support_tickets"),
    ("tracking", "sj_tracking"),
    ("coachMarks", "sj_coach_marks"),
]


async def main():
    from app.config.database import get_async_session_factory

    if not get_async_session_factory():
        print("Could not create session factory. Check DATABASE_URL.")
        sys.exit(1)
    print("Migrating JSON data to Oracle...")
    total = 0
    # Users (full table)
    n = await migrate_users()
    total += n
    print(f"  users -> sj_users: {n}")
    # Document-style tables
    for collection, table in DOC_COLLECTIONS:
        n = await migrate_doc_table(collection, table)
        total += n
        if n:
            print(f"  {collection} -> {table}: {n}")
    print(f"Done. Total rows migrated: {total}")


if __name__ == "__main__":
    asyncio.run(main())
