-- Migration: Add OTP table for secure OTP storage with TTL
-- Run as application user.

CREATE TABLE sj_otps (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  phone        VARCHAR2(20) NOT NULL,
  device_key   VARCHAR2(128) DEFAULT 'default' NOT NULL,
  otp_code     VARCHAR2(10) NOT NULL,
  verify_attempts NUMBER DEFAULT 0,
  created_at   TIMESTAMP NOT NULL,
  expires_at   TIMESTAMP NOT NULL,
  last_sent_at TIMESTAMP NOT NULL
);

CREATE INDEX ix_sj_otps_phone ON sj_otps (phone);
CREATE INDEX ix_sj_otps_expires ON sj_otps (expires_at);
CREATE INDEX ix_sj_otps_phone_device ON sj_otps (phone, device_key);

-- Hourly send tracking per phone number (user-level rate limiting)
CREATE TABLE sj_otp_send_log (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  phone        VARCHAR2(20) NOT NULL,
  sent_at      TIMESTAMP NOT NULL
);

CREATE INDEX ix_sj_otp_send_log_phone ON sj_otp_send_log (phone);
CREATE INDEX ix_sj_otp_send_log_sent ON sj_otp_send_log (sent_at);
