-- Oracle schema for Stationery Junction (Always Free / compatible)
-- Run as application user. Uses IDENTITY PKs and external_id for API compatibility.
-- Table prefix sj_ (Stationery Junction) avoids reserved words (USER, ORDER, etc.).

-- ========== USERS ==========
CREATE TABLE sj_users (
  user_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id_formatted VARCHAR2(32),
  name         VARCHAR2(255),
  email        VARCHAR2(255),
  password_hash VARCHAR2(255),
  role         VARCHAR2(32),
  phone        VARCHAR2(64),
  company_name VARCHAR2(255),
  address      CLOB,
  saved_addresses CLOB,
  is_active    NUMBER(1) DEFAULT 1,
  approval_status VARCHAR2(32),
  is_deactivated NUMBER(1) DEFAULT 0,
  credit_limit NUMBER(18,2) DEFAULT 0,
  credit_used  NUMBER(18,2) DEFAULT 0,
  payment_terms VARCHAR2(32),
  assigned_salesperson VARCHAR2(32),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_users_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_users_email ON sj_users (email);
CREATE INDEX ix_sj_users_phone ON sj_users (phone);
CREATE INDEX ix_sj_users_role ON sj_users (role);

-- ========== CATEGORIES ==========
CREATE TABLE sj_categories (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(255),
  description  VARCHAR2(4000),
  images       CLOB,
  sub_categories CLOB,
  is_active    NUMBER(1) DEFAULT 1,
  category_tag VARCHAR2(128),
  category_tags CLOB,
  minimum_quantity NUMBER DEFAULT 0,
  show_in_mobile_homepage NUMBER(1) DEFAULT 1,
  gst          NUMBER(5,2) DEFAULT 0,
  is_returnable NUMBER(1) DEFAULT 0,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_categories_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_categories_active ON sj_categories (is_active);

-- ========== BRANDS ==========
CREATE TABLE sj_brands (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(255),
  slug         VARCHAR2(255),
  image_url    VARCHAR2(1024),
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_brands_external UNIQUE (external_id)
);

-- ========== PRODUCTS ==========
CREATE TABLE sj_products (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(500),
  description  CLOB,
  sku          VARCHAR2(64),
  category     VARCHAR2(255),
  sub_category VARCHAR2(255),
  brand        VARCHAR2(255),
  mrp          NUMBER(18,2),
  mrp_per_case NUMBER(18,2),
  quantity_per_case NUMBER,
  stock        NUMBER DEFAULT 0,
  images       CLOB,
  videos       CLOB,
  is_active    NUMBER(1) DEFAULT 1,
  tags         CLOB,
  variant_attributes CLOB,
  variant_combinations CLOB,
  details      CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_products_external UNIQUE (external_id)
);
CREATE UNIQUE INDEX ix_sj_products_sku ON sj_products (sku);
CREATE INDEX ix_sj_products_active ON sj_products (is_active);
CREATE INDEX ix_sj_products_category ON sj_products (category);

-- ========== ORDERS (user_id FK) ==========
CREATE TABLE sj_orders (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  order_number VARCHAR2(64) NOT NULL,
  status       VARCHAR2(32),
  total        NUMBER(18,2),
  subtotal     NUMBER(18,2),
  tax          NUMBER(18,2) DEFAULT 0,
  shipping     NUMBER(18,2) DEFAULT 0,
  discount     NUMBER(18,2) DEFAULT 0,
  order_type   VARCHAR2(32),
  payment_status VARCHAR2(32),
  payment_method VARCHAR2(32),
  upi_payment_screenshot CLOB,
  shipping_address CLOB,
  billing_address CLOB,
  notes        VARCHAR2(4000),
  printed_bill NUMBER(1) DEFAULT 0,
  assigned_valet VARCHAR2(32),
  shipped_at   TIMESTAMP,
  delivered_at TIMESTAMP,
  cod_payment_received NUMBER(1) DEFAULT 0,
  cod_payment_received_at TIMESTAMP,
  decline_reason VARCHAR2(4000),
  cancelled_at TIMESTAMP,
  cancelled_by VARCHAR2(32),
  turnaround_hours NUMBER(10,2),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_orders_external UNIQUE (external_id),
  CONSTRAINT fk_sj_orders_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_orders_user ON sj_orders (user_id);
CREATE INDEX ix_sj_orders_status ON sj_orders (status);
CREATE INDEX ix_sj_orders_created ON sj_orders (created_at);
CREATE UNIQUE INDEX ix_sj_orders_order_number ON sj_orders (order_number);

-- ========== ORDER ITEMS ==========
CREATE TABLE sj_order_items (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_id     NUMBER NOT NULL,
  product_id   NUMBER NOT NULL,
  quantity     NUMBER NOT NULL,
  price        NUMBER(18,2) NOT NULL,
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES sj_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES sj_products (id)
);
CREATE INDEX ix_sj_order_items_order ON sj_order_items (order_id);
CREATE INDEX ix_sj_order_items_product ON sj_order_items (product_id);

-- ========== CARTS ==========
CREATE TABLE sj_carts (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  items        CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_carts_external UNIQUE (external_id),
  CONSTRAINT fk_sj_carts_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_carts_user ON sj_carts (user_id);

-- ========== WISHLISTS ==========
CREATE TABLE sj_wishlists (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  items        CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_wishlists_external UNIQUE (external_id),
  CONSTRAINT fk_sj_wishlists_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_wishlists_user ON sj_wishlists (user_id);

-- ========== SESSIONS ==========
CREATE TABLE sj_sessions (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  refresh_token_id VARCHAR2(64),
  status       VARCHAR2(32),
  last_active_at TIMESTAMP,
  revoked_at   TIMESTAMP,
  revoked_reason VARCHAR2(64),
  device       CLOB,
  is_guest     NUMBER(1) DEFAULT 0,
  comments     VARCHAR2(4000),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_sessions_external UNIQUE (external_id),
  CONSTRAINT fk_sj_sessions_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_sessions_user ON sj_sessions (user_id);
CREATE INDEX ix_sj_sessions_status ON sj_sessions (status);
CREATE INDEX ix_sj_sessions_refresh ON sj_sessions (refresh_token_id);

-- ========== COUPONS ==========
CREATE TABLE sj_coupons (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  code         VARCHAR2(64),
  discount_type VARCHAR2(32),
  discount_value NUMBER(18,2),
  min_order_value NUMBER(18,2),
  max_uses     NUMBER,
  used_count   NUMBER DEFAULT 0,
  start_date   TIMESTAMP,
  end_date     TIMESTAMP,
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_coupons_external UNIQUE (external_id)
);
CREATE UNIQUE INDEX ix_sj_coupons_code ON sj_coupons (UPPER(code));

-- ========== BANNERS ==========
CREATE TABLE sj_banners (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  title        VARCHAR2(255),
  description  VARCHAR2(4000),
  image_url    VARCHAR2(1024),
  link_url     VARCHAR2(1024),
  display_order NUMBER DEFAULT 0,
  start_date   VARCHAR2(32),
  end_date     VARCHAR2(32),
  is_active    NUMBER(1) DEFAULT 1,
  is_published NUMBER(1) DEFAULT 1,
  target_audience VARCHAR2(32),
  position     VARCHAR2(64),
  user_segments CLOB,
  visibility_rules CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_banners_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_banners_active ON sj_banners (is_active);

-- ========== DELIVERY CHARGES ==========
CREATE TABLE sj_delivery_charges (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_delivery_charges_external UNIQUE (external_id)
);

CREATE TABLE sj_delivery_charge_defaults (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_dc_defaults_external UNIQUE (external_id)
);

-- ========== DOCUMENT-STYLE TABLES (flexible payload) ==========
-- Use for entities with variable or rarely-filtered structure; id + external_id + doc CLOB.

CREATE TABLE sj_order_feedback (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_order_feedback_external UNIQUE (external_id)
);

CREATE TABLE sj_contacts (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_contacts_external UNIQUE (external_id)
);

CREATE TABLE sj_support_tickets (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_support_tickets_external UNIQUE (external_id)
);

CREATE TABLE sj_tracking (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_tracking_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_tracking_created ON sj_tracking (created_at);

CREATE TABLE sj_saved_for_later (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_saved_for_later_external UNIQUE (external_id)
);

CREATE TABLE sj_payments (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_payments_external UNIQUE (external_id)
);

CREATE TABLE sj_feature_flags (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  flag_id      VARCHAR2(128) NOT NULL,
  name         VARCHAR2(255),
  description  VARCHAR2(4000),
  enabled      NUMBER(1) DEFAULT 1,
  category     VARCHAR2(64),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_feature_flags_flag_id UNIQUE (flag_id)
);

CREATE TABLE sj_notifications (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_notifications_external UNIQUE (external_id)
);

CREATE TABLE sj_category_tags (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_category_tags_external UNIQUE (external_id)
);

CREATE TABLE sj_push_notifications (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_push_notifications_external UNIQUE (external_id)
);

CREATE TABLE sj_device_subscriptions (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_device_subscriptions_external UNIQUE (external_id)
);

CREATE TABLE sj_activities (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_activities_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_activities_created ON sj_activities (created_at);

CREATE TABLE sj_promo_strips (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_promo_strips_external UNIQUE (external_id)
);

CREATE TABLE sj_collections (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_collections_external UNIQUE (external_id)
);

CREATE TABLE sj_search_tags (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_search_tags_external UNIQUE (external_id)
);

CREATE TABLE sj_coach_marks (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_coach_marks_external UNIQUE (external_id)
);

CREATE TABLE sj_events (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_events_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_events_created ON sj_events (created_at);

-- ========== REMAINING COLLECTIONS (Document-style) ==========
-- These are used by existing repositories and should not fall back to JSON when DATABASE_URL is set.

CREATE TABLE sj_schemes (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_schemes_external UNIQUE (external_id)
);

CREATE TABLE sj_google_reviews (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_google_reviews_external UNIQUE (external_id)
);

CREATE TABLE sj_customer_segments (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_customer_segments_external UNIQUE (external_id)
);

CREATE TABLE sj_referral_settings (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_referral_settings_external UNIQUE (external_id)
);

CREATE TABLE sj_return_settings (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_return_settings_external UNIQUE (external_id)
);

CREATE TABLE sj_return_requests (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  doc          CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_return_requests_external UNIQUE (external_id)
);
