-- =============================================================================
-- Oracle schema: relational + JSON hybrid.
-- Fixed fields are stored in typed columns. Variable arrays/objects are stored in JSON columns.
-- Includes child/detail tables where explicitly modeled (e.g. sj_payment_entries).
-- For Oracle 21c+: JSON columns use native JSON type.
-- For Oracle 19c: replace JSON columns with CLOB (optionally add CHECK (col IS JSON)),
-- or use backend/scripts/fix_and_apply_oracle_schema.py which converts JSON -> CLOB.
-- Run after dropping old schema objects.
-- =============================================================================

-- ========== TRACKING (typed + product_ids JSON, payload JSON for rest) ==========
CREATE TABLE sj_tracking (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id       VARCHAR2(32) NOT NULL,
  event_type        VARCHAR2(64),
  user_id           VARCHAR2(32),
  session_id        VARCHAR2(64),
  event_timestamp    TIMESTAMP,
  search_term       VARCHAR2(500),
  product_id        VARCHAR2(32),
  product_name      VARCHAR2(500),
  results_count     NUMBER,
  segment           VARCHAR2(32),
  page              VARCHAR2(255),
  reason            VARCHAR2(500),
  filter_type       VARCHAR2(64),
  filter_value      VARCHAR2(255),
  source            VARCHAR2(64),
  cart_value        NUMBER(18,2),
  product_ids       JSON,
  payload           JSON,
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_tracking_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_tracking_created ON sj_tracking (created_at);
CREATE INDEX ix_sj_tracking_type ON sj_tracking (event_type);
CREATE INDEX ix_sj_tracking_user ON sj_tracking (user_id);
CREATE INDEX ix_sj_tracking_timestamp ON sj_tracking (event_timestamp);

-- ========== ACTIVITIES (device as fixed columns, meta as JSON) ==========
CREATE TABLE sj_activities (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  user_id       VARCHAR2(32),
  session_id    VARCHAR2(64),
  action        VARCHAR2(128),
  comments      VARCHAR2(4000),
  is_guest      NUMBER(1) DEFAULT 0,
  user_agent    VARCHAR2(1024),
  os            VARCHAR2(128),
  os_version    VARCHAR2(64),
  device_type   VARCHAR2(64),
  app_version   VARCHAR2(64),
  device_model  VARCHAR2(128),
  locale        VARCHAR2(128),
  ip            VARCHAR2(64),
  meta          JSON,
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_activities_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_activities_created ON sj_activities (created_at);
CREATE INDEX ix_sj_activities_session ON sj_activities (session_id);

-- ========== NOTIFICATIONS (data as JSON) ==========
CREATE TABLE sj_notifications (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id     VARCHAR2(32) NOT NULL,
  user_id         VARCHAR2(32),
  type            VARCHAR2(64),
  title           VARCHAR2(500),
  message         VARCHAR2(4000),
  is_read         NUMBER(1) DEFAULT 0,
  is_acknowledged NUMBER(1) DEFAULT 0,
  data            JSON,
  created_at      TIMESTAMP,
  updated_at      TIMESTAMP,
  CONSTRAINT uq_sj_notifications_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_notifications_user ON sj_notifications (user_id);
CREATE INDEX ix_sj_notifications_type ON sj_notifications (type);
CREATE INDEX ix_sj_notifications_created ON sj_notifications (created_at);

-- ========== PAYMENTS (payment header; entries in sj_payment_entries) ==========
CREATE TABLE sj_payments (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id        VARCHAR2(32) NOT NULL,
  order_id           VARCHAR2(32),
  user_id            VARCHAR2(32),
  user_id_formatted  VARCHAR2(32),
  customer_name      VARCHAR2(255),
  order_date         TIMESTAMP,
  payment_method     VARCHAR2(32),
  amount_paid        NUMBER(18,2),
  amount_remaining   NUMBER(18,2),
  total_amount       NUMBER(18,2),
  payment_id         VARCHAR2(32),
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_payments_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_payments_order ON sj_payments (order_id);
CREATE INDEX ix_sj_payments_user ON sj_payments (user_id);

-- ========== PAYMENT ENTRIES (one row per entry; FK to payment) ==========
CREATE TABLE sj_payment_entries (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  payment_id       NUMBER NOT NULL,
  entry_id        NUMBER DEFAULT 1,
  amount          NUMBER(18,2),
  payment_method  VARCHAR2(32),
  paid_at         TIMESTAMP,
  image           VARCHAR2(1024),
  notes           VARCHAR2(4000),
  verified        NUMBER(1) DEFAULT 0,
  created_at      TIMESTAMP,
  CONSTRAINT fk_payment_entries_payment FOREIGN KEY (payment_id) REFERENCES sj_payments (id) ON DELETE CASCADE
);
CREATE INDEX ix_sj_payment_entries_payment ON sj_payment_entries (payment_id);

-- ========== RETURN REQUESTS (items as JSON) ==========
CREATE TABLE sj_return_requests (
  id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id           VARCHAR2(32) NOT NULL,
  return_id             VARCHAR2(32),
  order_id              VARCHAR2(32),
  user_id               VARCHAR2(32),
  payment_method        VARCHAR2(32),
  upi_payment_screenshot VARCHAR2(2000),
  notes                 VARCHAR2(4000),
  status                VARCHAR2(32),
  valet_id              VARCHAR2(32),
  delivery_charge       NUMBER(18,2),
  items                 JSON,
  created_at            TIMESTAMP,
  updated_at            TIMESTAMP,
  CONSTRAINT uq_sj_return_requests_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_return_requests_order ON sj_return_requests (order_id);
CREATE INDEX ix_sj_return_requests_user ON sj_return_requests (user_id);

-- ========== RETURN SETTINGS (single row) ==========
CREATE TABLE sj_return_settings (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  return_days  NUMBER DEFAULT 7,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_return_settings_external UNIQUE (external_id)
);

-- ========== SCHEMES (applicable_roles as JSON) ==========
CREATE TABLE sj_schemes (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id       VARCHAR2(32) NOT NULL,
  name              VARCHAR2(255),
  description       VARCHAR2(4000),
  discount_type     VARCHAR2(32),
  discount_value    NUMBER(18,2),
  min_order_value   NUMBER(18,2),
  valid_from        TIMESTAMP,
  valid_until       TIMESTAMP,
  is_active         NUMBER(1) DEFAULT 1,
  code              VARCHAR2(64),
  applicable_roles  JSON,
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_schemes_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_schemes_active ON sj_schemes (is_active);

-- ========== CONTACTS (addresses + phone_numbers as JSON) ==========
CREATE TABLE sj_contacts (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  email         VARCHAR2(255),
  description   VARCHAR2(4000),
  is_active     NUMBER(1) DEFAULT 1,
  display_order NUMBER DEFAULT 0,
  addresses     JSON,
  phone_numbers JSON,
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_contacts_external UNIQUE (external_id)
);

-- ========== SUPPORT TICKETS (description as text; attachments + responses as JSON) ==========
CREATE TABLE sj_support_tickets (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  ticket_number VARCHAR2(64),
  user_id       VARCHAR2(32),
  name          VARCHAR2(255),
  email         VARCHAR2(255),
  phone         VARCHAR2(64),
  company       VARCHAR2(255),
  subject       VARCHAR2(500),
  description   VARCHAR2(4000),
  category      VARCHAR2(64),
  priority      VARCHAR2(32),
  status        VARCHAR2(32),
  assigned_to   VARCHAR2(32),
  resolved_at   TIMESTAMP,
  closed_at     TIMESTAMP,
  attachments   JSON,
  responses     JSON,
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_support_tickets_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_support_tickets_user ON sj_support_tickets (user_id);
CREATE INDEX ix_sj_support_tickets_status ON sj_support_tickets (status);

-- ========== ORDER FEEDBACK (all fixed columns) ==========
CREATE TABLE sj_order_feedback (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id      VARCHAR2(32) NOT NULL,
  order_id         VARCHAR2(32),
  user_id          VARCHAR2(32),
  rating           NUMBER,
  comments         VARCHAR2(4000),
  delivery_rating  NUMBER,
  delivery_comment VARCHAR2(4000),
  feedback_type    VARCHAR2(32),
  created_at       TIMESTAMP,
  updated_at       TIMESTAMP,
  CONSTRAINT uq_sj_order_feedback_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_order_feedback_order ON sj_order_feedback (order_id);
CREATE INDEX ix_sj_order_feedback_user ON sj_order_feedback (user_id);

-- ========== PROMO STRIPS (all fixed) ==========
CREATE TABLE sj_promo_strips (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  text         VARCHAR2(2000),
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_promo_strips_external UNIQUE (external_id)
);

-- ========== PUSH NOTIFICATIONS (all fixed) ==========
CREATE TABLE sj_push_notifications (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id     VARCHAR2(32) NOT NULL,
  title           VARCHAR2(500),
  message         VARCHAR2(4000),
  link            VARCHAR2(1024),
  image           VARCHAR2(1024),
  status          VARCHAR2(32),
  scheduled_for   TIMESTAMP,
  delivered_count NUMBER DEFAULT 0,
  read_count      NUMBER DEFAULT 0,
  user_segment    VARCHAR2(64),
  user_behavior   VARCHAR2(64),
  created_by      VARCHAR2(32),
  created_at      TIMESTAMP,
  updated_at      TIMESTAMP,
  CONSTRAINT uq_sj_push_notifications_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_push_notifications_status ON sj_push_notifications (status);

-- ========== DEVICE SUBSCRIPTIONS (keys + subscription as JSON) ==========
CREATE TABLE sj_device_subscriptions (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      VARCHAR2(32),
  endpoint     VARCHAR2(2000),
  expo_token   VARCHAR2(500),
  keys         JSON,
  subscription JSON,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_device_subscriptions_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_device_subscriptions_user ON sj_device_subscriptions (user_id);
CREATE INDEX ix_sj_device_subscriptions_endpoint ON sj_device_subscriptions (endpoint);

-- ========== COLLECTIONS (arrays as JSON) ==========
CREATE TABLE sj_collections (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id       VARCHAR2(32) NOT NULL,
  name              VARCHAR2(255),
  description       VARCHAR2(4000),
  image_url         VARCHAR2(1024),
  is_active         NUMBER(1) DEFAULT 1,
  display_order     NUMBER DEFAULT 0,
  visible_pages     JSON,
  user_segments     JSON,
  visibility_rules  JSON,
  product_ids       JSON,
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_collections_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_collections_active ON sj_collections (is_active);

-- ========== SEARCH TAGS (arrays as JSON) ==========
CREATE TABLE sj_search_tags (
  id                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id          VARCHAR2(32) NOT NULL,
  tag_id               VARCHAR2(64),
  name                 VARCHAR2(255),
  type                 VARCHAR2(64),
  is_active            NUMBER(1) DEFAULT 1,
  categories           JSON,
  sub_categories       JSON,
  brands               JSON,
  collections          JSON,
  product_ids          JSON,
  excluded_product_ids JSON,
  created_at           TIMESTAMP,
  updated_at            TIMESTAMP,
  CONSTRAINT uq_sj_search_tags_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_search_tags_active ON sj_search_tags (is_active);

-- ========== COACH MARKS (all fixed) ==========
CREATE TABLE sj_coach_marks (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id    VARCHAR2(32) NOT NULL,
  anchor_id      VARCHAR2(128),
  title          VARCHAR2(255),
  description    VARCHAR2(4000),
  screen_name    VARCHAR2(128),
  sequence_order NUMBER DEFAULT 0,
  is_active      NUMBER(1) DEFAULT 1,
  created_at     TIMESTAMP,
  updated_at     TIMESTAMP,
  CONSTRAINT uq_sj_coach_marks_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_coach_marks_anchor ON sj_coach_marks (anchor_id);

-- ========== CATEGORY TAGS (all fixed) ==========
CREATE TABLE sj_category_tags (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(255),
  description  VARCHAR2(4000),
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_category_tags_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_category_tags_name ON sj_category_tags (name);

-- ========== DELIVERY CHARGES (tiers as JSON) ==========
CREATE TABLE sj_delivery_charges (
  id                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id             VARCHAR2(32) NOT NULL,
  location_id             NUMBER,
  pincode                 VARCHAR2(32),
  state                   VARCHAR2(128),
  city                    VARCHAR2(128),
  district                VARCHAR2(128),
  apply_default_charge    NUMBER(1) DEFAULT 0,
  charge                  NUMBER(18,2),
  min_cart_value          NUMBER(18,2),
  tiers                   JSON,
  serviceable_for_customer NUMBER(1) DEFAULT 0,
  serviceable_for_retailer NUMBER(1) DEFAULT 0,
  serviceable_for_wholesaler NUMBER(1) DEFAULT 0,
  is_active               NUMBER(1) DEFAULT 1,
  description             VARCHAR2(4000),
  created_at              TIMESTAMP,
  updated_at              TIMESTAMP,
  CONSTRAINT uq_sj_delivery_charges_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_delivery_charges_pincode ON sj_delivery_charges (pincode);
CREATE INDEX ix_sj_delivery_charges_active ON sj_delivery_charges (is_active);

-- ========== DELIVERY CHARGE DEFAULTS (tiers as JSON) ==========
CREATE TABLE sj_delivery_charge_defaults (
  id                       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id              VARCHAR2(32) NOT NULL,
  tiers                    JSON,
  applicable_to_wholesaler NUMBER(1) DEFAULT 1,
  applicable_to_retailer   NUMBER(1) DEFAULT 1,
  is_active                NUMBER(1) DEFAULT 1,
  created_at               TIMESTAMP,
  updated_at               TIMESTAMP,
  CONSTRAINT uq_sj_dc_defaults_external UNIQUE (external_id)
);

-- ========== SAVED FOR LATER (one row per user+product; no JSON) ==========
CREATE TABLE sj_saved_for_later (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      VARCHAR2(32) NOT NULL,
  product_id   VARCHAR2(32) NOT NULL,
  saved_at     TIMESTAMP,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_saved_for_later_external UNIQUE (external_id),
  CONSTRAINT uq_sfl_user_product UNIQUE (user_id, product_id)
);
CREATE INDEX ix_sj_saved_for_later_user ON sj_saved_for_later (user_id);

-- ========== REFERRAL SETTINGS (one row per segment: retail / business; typed columns) ==========
CREATE TABLE sj_referral_settings (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id    VARCHAR2(32) NOT NULL,
  segment        VARCHAR2(32) NOT NULL,
  discount_type  VARCHAR2(32),
  discount_value NUMBER(18,2) DEFAULT 0,
  is_active      NUMBER(1) DEFAULT 0,
  created_at     TIMESTAMP,
  updated_at     TIMESTAMP,
  CONSTRAINT uq_sj_referral_settings_external UNIQUE (external_id),
  CONSTRAINT uq_sj_referral_settings_segment UNIQUE (segment)
);
CREATE INDEX ix_sj_referral_settings_segment ON sj_referral_settings (segment);

-- ========== EVENTS (payload as JSON) ==========
CREATE TABLE sj_events (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  event_type   VARCHAR2(64),
  payload      JSON,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_events_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_events_created ON sj_events (created_at);
CREATE INDEX ix_sj_events_type ON sj_events (event_type);

-- ========== CUSTOMER SEGMENTS (payload as JSON for variable fields) ==========
CREATE TABLE sj_customer_segments (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  type         VARCHAR2(64),
  payload      JSON,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_customer_segments_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_customer_segments_type ON sj_customer_segments (type);

-- ========== GOOGLE REVIEWS (all fixed) ==========
CREATE TABLE sj_google_reviews (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  rating        NUMBER(3,2),
  review_count  VARCHAR2(32),
  last_updated  VARCHAR2(64),
  method        VARCHAR2(32),
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_google_reviews_external UNIQUE (external_id)
);
