-- =============================================================================
-- Unified Oracle 19c Schema for Stationery Junction
-- Merged Core Tables + Modernized Typed Tables (clob-based JSON)
-- Compatibility: Oracle Database 19c Enterprise/Autonomous (No 21c native JSON)
-- =============================================================================

-- ========== 1. CORE RELATIONAL TABLES ==========

-- USERS
CREATE TABLE sj_users (
  user_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id_formatted VARCHAR2(32),
  name         VARCHAR2(255),
  email        VARCHAR2(255),
  password_hash VARCHAR2(255),
  role         VARCHAR2(32),
  phone        VARCHAR2(64),
  company_name VARCHAR2(255),
  address      CLOB,
  saved_addresses CLOB,
  is_active    NUMBER(1) DEFAULT 1,
  approval_status VARCHAR2(32),
  is_deactivated NUMBER(1) DEFAULT 0,
  credit_limit NUMBER(18,2) DEFAULT 0,
  credit_used  NUMBER(18,2) DEFAULT 0,
  payment_terms VARCHAR2(32),
  assigned_salesperson VARCHAR2(32),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_users_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_users_email ON sj_users (email);
CREATE INDEX ix_sj_users_phone ON sj_users (phone);
CREATE INDEX ix_sj_users_role ON sj_users (role);

-- CATEGORIES
CREATE TABLE sj_categories (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(255),
  description  VARCHAR2(4000),
  images       CLOB,
  sub_categories CLOB,
  is_active    NUMBER(1) DEFAULT 1,
  category_tag VARCHAR2(128),
  category_tags CLOB,
  minimum_quantity NUMBER DEFAULT 0,
  show_in_mobile_homepage NUMBER(1) DEFAULT 1,
  gst          NUMBER(5,2) DEFAULT 0,
  is_returnable NUMBER(1) DEFAULT 0,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_categories_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_categories_active ON sj_categories (is_active);

-- BRANDS
CREATE TABLE sj_brands (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(255),
  slug         VARCHAR2(255),
  image_url    VARCHAR2(1024),
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_brands_external UNIQUE (external_id)
);

-- PRODUCTS
CREATE TABLE sj_products (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(500),
  description  CLOB,
  sku          VARCHAR2(64),
  category     VARCHAR2(255),
  sub_category VARCHAR2(255),
  brand        VARCHAR2(255),
  mrp          NUMBER(18,2),
  mrp_per_case NUMBER(18,2),
  quantity_per_case NUMBER,
  stock        NUMBER DEFAULT 0,
  images       CLOB,
  videos       CLOB,
  is_active    NUMBER(1) DEFAULT 1,
  tags         CLOB,
  variant_attributes CLOB,
  variant_combinations CLOB,
  details      CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_products_external UNIQUE (external_id)
);
CREATE UNIQUE INDEX ix_sj_products_sku ON sj_products (sku);
CREATE INDEX ix_sj_products_active ON sj_products (is_active);
CREATE INDEX ix_sj_products_category ON sj_products (category);

-- ORDERS
CREATE TABLE sj_orders (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  order_number VARCHAR2(64) NOT NULL,
  status       VARCHAR2(32),
  total        NUMBER(18,2),
  subtotal     NUMBER(18,2),
  tax          NUMBER(18,2) DEFAULT 0,
  shipping     NUMBER(18,2) DEFAULT 0,
  discount     NUMBER(18,2) DEFAULT 0,
  order_type   VARCHAR2(32),
  payment_status VARCHAR2(32),
  payment_method VARCHAR2(32),
  upi_payment_screenshot CLOB,
  shipping_address CLOB,
  billing_address CLOB,
  notes        VARCHAR2(4000),
  printed_bill NUMBER(1) DEFAULT 0,
  assigned_valet VARCHAR2(32),
  shipped_at   TIMESTAMP,
  delivered_at TIMESTAMP,
  cod_payment_received NUMBER(1) DEFAULT 0,
  cod_payment_received_at TIMESTAMP,
  decline_reason VARCHAR2(4000),
  cancelled_at TIMESTAMP,
  cancelled_by VARCHAR2(32),
  turnaround_hours NUMBER(10,2),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_orders_external UNIQUE (external_id),
  CONSTRAINT fk_sj_orders_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_orders_user ON sj_orders (user_id);
CREATE INDEX ix_sj_orders_status ON sj_orders (status);
CREATE INDEX ix_sj_orders_created ON sj_orders (created_at);
CREATE UNIQUE INDEX ix_sj_orders_order_number ON sj_orders (order_number);

-- ORDER ITEMS
CREATE TABLE sj_order_items (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_id     NUMBER NOT NULL,
  product_id   NUMBER NOT NULL,
  quantity     NUMBER NOT NULL,
  price        NUMBER(18,2) NOT NULL,
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES sj_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES sj_products (id)
);
CREATE INDEX ix_sj_order_items_order ON sj_order_items (order_id);
CREATE INDEX ix_sj_order_items_product ON sj_order_items (product_id);

-- CARTS
CREATE TABLE sj_carts (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  items        CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_carts_external UNIQUE (external_id),
  CONSTRAINT fk_sj_carts_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_carts_user ON sj_carts (user_id);

-- WISHLISTS
CREATE TABLE sj_wishlists (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  items        CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_wishlists_external UNIQUE (external_id),
  CONSTRAINT fk_sj_wishlists_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_wishlists_user ON sj_wishlists (user_id);

-- SESSIONS
CREATE TABLE sj_sessions (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      NUMBER NOT NULL,
  refresh_token_id VARCHAR2(64),
  status       VARCHAR2(32),
  last_active_at TIMESTAMP,
  revoked_at   TIMESTAMP,
  revoked_reason VARCHAR2(64),
  device       CLOB,
  is_guest     NUMBER(1) DEFAULT 0,
  comments     VARCHAR2(4000),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_sessions_external UNIQUE (external_id),
  CONSTRAINT fk_sj_sessions_user FOREIGN KEY (user_id) REFERENCES sj_users (user_id)
);
CREATE INDEX ix_sj_sessions_user ON sj_sessions (user_id);
CREATE INDEX ix_sj_sessions_status ON sj_sessions (status);
CREATE INDEX ix_sj_sessions_refresh ON sj_sessions (refresh_token_id);

-- COUPONS
CREATE TABLE sj_coupons (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  code         VARCHAR2(64),
  discount_type VARCHAR2(32),
  discount_value NUMBER(18,2),
  min_order_value NUMBER(18,2),
  max_uses     NUMBER,
  used_count   NUMBER DEFAULT 0,
  start_date   TIMESTAMP,
  end_date     TIMESTAMP,
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_coupons_external UNIQUE (external_id)
);
CREATE UNIQUE INDEX ix_sj_coupons_code ON sj_coupons (UPPER(code));

-- BANNERS
CREATE TABLE sj_banners (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  title        VARCHAR2(255),
  description  VARCHAR2(4000),
  image_url    VARCHAR2(1024),
  link_url     VARCHAR2(1024),
  display_order NUMBER DEFAULT 0,
  start_date   VARCHAR2(32),
  end_date     VARCHAR2(32),
  is_active    NUMBER(1) DEFAULT 1,
  is_published NUMBER(1) DEFAULT 1,
  target_audience VARCHAR2(32),
  position     VARCHAR2(64),
  user_segments CLOB,
  visibility_rules CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_banners_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_banners_active ON sj_banners (is_active);

-- ========== 2. TYPED OPERATIONAL TABLES (19c COMPATIBLE CLOB) ==========

-- TRACKING
CREATE TABLE sj_tracking (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id       VARCHAR2(32) NOT NULL,
  event_type        VARCHAR2(64),
  user_id           VARCHAR2(32),
  session_id        VARCHAR2(64),
  event_timestamp   TIMESTAMP,
  search_term       VARCHAR2(500),
  product_id        VARCHAR2(32),
  product_name      VARCHAR2(500),
  results_count     NUMBER,
  segment           VARCHAR2(32),
  page              VARCHAR2(255),
  reason            VARCHAR2(500),
  filter_type       VARCHAR2(64),
  filter_value      VARCHAR2(255),
  source            VARCHAR2(64),
  cart_value        NUMBER(18,2),
  product_ids       CLOB,
  payload           CLOB,
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_tracking_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_tracking_created ON sj_tracking (created_at);
CREATE INDEX ix_sj_tracking_type ON sj_tracking (event_type);
CREATE INDEX ix_sj_tracking_user ON sj_tracking (user_id);
CREATE INDEX ix_sj_tracking_timestamp ON sj_tracking (event_timestamp);

-- ACTIVITIES
CREATE TABLE sj_activities (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  user_id       VARCHAR2(32),
  session_id    VARCHAR2(64),
  action        VARCHAR2(128),
  comments      VARCHAR2(4000),
  is_guest      NUMBER(1) DEFAULT 0,
  user_agent    VARCHAR2(1024),
  os            VARCHAR2(128),
  os_version    VARCHAR2(64),
  device_type   VARCHAR2(64),
  app_version   VARCHAR2(64),
  device_model  VARCHAR2(128),
  locale        VARCHAR2(128),
  ip            VARCHAR2(64),
  meta          CLOB,
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_activities_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_activities_created ON sj_activities (created_at);
CREATE INDEX ix_sj_activities_session ON sj_activities (session_id);

-- NOTIFICATIONS
CREATE TABLE sj_notifications (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id     VARCHAR2(32) NOT NULL,
  user_id         VARCHAR2(32),
  type            VARCHAR2(64),
  title           VARCHAR2(500),
  message         VARCHAR2(4000),
  is_read         NUMBER(1) DEFAULT 0,
  is_acknowledged NUMBER(1) DEFAULT 0,
  data            CLOB,
  created_at      TIMESTAMP,
  updated_at      TIMESTAMP,
  CONSTRAINT uq_sj_notifications_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_notifications_user ON sj_notifications (user_id);
CREATE INDEX ix_sj_notifications_type ON sj_notifications (type);
CREATE INDEX ix_sj_notifications_created ON sj_notifications (created_at);

-- PAYMENTS
CREATE TABLE sj_payments (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id        VARCHAR2(32) NOT NULL,
  order_id           VARCHAR2(32),
  user_id            VARCHAR2(32),
  user_id_formatted  VARCHAR2(32),
  customer_name      VARCHAR2(255),
  order_date         TIMESTAMP,
  payment_method     VARCHAR2(32),
  amount_paid        NUMBER(18,2),
  amount_remaining   NUMBER(18,2),
  total_amount       NUMBER(18,2),
  payment_id         VARCHAR2(32),
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_payments_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_payments_order ON sj_payments (order_id);
CREATE INDEX ix_sj_payments_user ON sj_payments (user_id);

-- PAYMENT ENTRIES
CREATE TABLE sj_payment_entries (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  payment_id       NUMBER NOT NULL,
  entry_id        NUMBER DEFAULT 1,
  amount          NUMBER(18,2),
  payment_method  VARCHAR2(32),
  paid_at         TIMESTAMP,
  image           VARCHAR2(1024),
  notes           VARCHAR2(4000),
  verified        NUMBER(1) DEFAULT 0,
  created_at      TIMESTAMP,
  CONSTRAINT fk_payment_entries_payment FOREIGN KEY (payment_id) REFERENCES sj_payments (id) ON DELETE CASCADE
);
CREATE INDEX ix_sj_payment_entries_payment ON sj_payment_entries (payment_id);

-- RETURN REQUESTS
CREATE TABLE sj_return_requests (
  id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id           VARCHAR2(32) NOT NULL,
  return_id             VARCHAR2(32),
  order_id              VARCHAR2(32),
  user_id               VARCHAR2(32),
  payment_method        VARCHAR2(32),
  upi_payment_screenshot VARCHAR2(2000),
  notes                 VARCHAR2(4000),
  status                VARCHAR2(32),
  valet_id              VARCHAR2(32),
  delivery_charge       NUMBER(18,2),
  items                 CLOB,
  created_at            TIMESTAMP,
  updated_at            TIMESTAMP,
  CONSTRAINT uq_sj_return_requests_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_return_requests_order ON sj_return_requests (order_id);
CREATE INDEX ix_sj_return_requests_user ON sj_return_requests (user_id);

-- RETURN SETTINGS
CREATE TABLE sj_return_settings (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  return_days  NUMBER DEFAULT 7,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_return_settings_external UNIQUE (external_id)
);

-- SCHEMES
CREATE TABLE sj_schemes (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id       VARCHAR2(32) NOT NULL,
  name              VARCHAR2(255),
  description       VARCHAR2(4000),
  discount_type     VARCHAR2(32),
  discount_value    NUMBER(18,2),
  min_order_value   NUMBER(18,2),
  valid_from        TIMESTAMP,
  valid_until       TIMESTAMP,
  is_active         NUMBER(1) DEFAULT 1,
  code              VARCHAR2(64),
  applicable_roles  CLOB,
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_schemes_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_schemes_active ON sj_schemes (is_active);

-- CONTACTS
CREATE TABLE sj_contacts (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  email         VARCHAR2(255),
  description   VARCHAR2(4000),
  is_active     NUMBER(1) DEFAULT 1,
  display_order NUMBER DEFAULT 0,
  addresses     CLOB,
  phone_numbers CLOB,
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_contacts_external UNIQUE (external_id)
);

-- SUPPORT TICKETS
CREATE TABLE sj_support_tickets (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  ticket_number VARCHAR2(64),
  user_id       VARCHAR2(32),
  name          VARCHAR2(255),
  email         VARCHAR2(255),
  phone         VARCHAR2(64),
  company       VARCHAR2(255),
  subject       VARCHAR2(500),
  description   VARCHAR2(4000),
  category      VARCHAR2(64),
  priority      VARCHAR2(32),
  status        VARCHAR2(32),
  assigned_to   VARCHAR2(32),
  resolved_at   TIMESTAMP,
  closed_at     TIMESTAMP,
  attachments   CLOB,
  responses     CLOB,
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_support_tickets_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_support_tickets_user ON sj_support_tickets (user_id);
CREATE INDEX ix_sj_support_tickets_status ON sj_support_tickets (status);

-- ORDER FEEDBACK
CREATE TABLE sj_order_feedback (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id      VARCHAR2(32) NOT NULL,
  order_id         VARCHAR2(32),
  user_id          VARCHAR2(32),
  rating           NUMBER,
  comments         VARCHAR2(4000),
  delivery_rating  NUMBER,
  delivery_comment VARCHAR2(4000),
  feedback_type    VARCHAR2(32),
  created_at       TIMESTAMP,
  updated_at       TIMESTAMP,
  CONSTRAINT uq_sj_order_feedback_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_order_feedback_order ON sj_order_feedback (order_id);
CREATE INDEX ix_sj_order_feedback_user ON sj_order_feedback (user_id);

-- PROMO STRIPS
CREATE TABLE sj_promo_strips (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  text         VARCHAR2(2000),
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_promo_strips_external UNIQUE (external_id)
);

-- PUSH NOTIFICATIONS
CREATE TABLE sj_push_notifications (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id     VARCHAR2(32) NOT NULL,
  title           VARCHAR2(500),
  message         VARCHAR2(4000),
  link            VARCHAR2(1024),
  image           VARCHAR2(1024),
  status          VARCHAR2(32),
  scheduled_for   TIMESTAMP,
  delivered_count NUMBER DEFAULT 0,
  read_count      NUMBER DEFAULT 0,
  user_segment    VARCHAR2(64),
  user_behavior   VARCHAR2(64),
  created_by      VARCHAR2(32),
  created_at      TIMESTAMP,
  updated_at      TIMESTAMP,
  CONSTRAINT uq_sj_push_notifications_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_push_notifications_status ON sj_push_notifications (status);

-- DEVICE SUBSCRIPTIONS
CREATE TABLE sj_device_subscriptions (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      VARCHAR2(32),
  endpoint     VARCHAR2(2000),
  expo_token   VARCHAR2(500),
  keys         CLOB,
  subscription CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_device_subscriptions_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_device_subscriptions_user ON sj_device_subscriptions (user_id);
CREATE INDEX ix_sj_device_subscriptions_endpoint ON sj_device_subscriptions (endpoint);

-- COLLECTIONS
CREATE TABLE sj_collections (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id       VARCHAR2(32) NOT NULL,
  name              VARCHAR2(255),
  description       VARCHAR2(4000),
  image_url         VARCHAR2(1024),
  is_active         NUMBER(1) DEFAULT 1,
  display_order     NUMBER DEFAULT 0,
  visible_pages     CLOB,
  user_segments     CLOB,
  visibility_rules  CLOB,
  product_ids       CLOB,
  created_at        TIMESTAMP,
  updated_at        TIMESTAMP,
  CONSTRAINT uq_sj_collections_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_collections_active ON sj_collections (is_active);

-- SEARCH TAGS
CREATE TABLE sj_search_tags (
  id                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id          VARCHAR2(32) NOT NULL,
  tag_id               VARCHAR2(64),
  name                 VARCHAR2(255),
  type                 VARCHAR2(64),
  is_active            NUMBER(1) DEFAULT 1,
  categories           CLOB,
  sub_categories       CLOB,
  brands               CLOB,
  collections          CLOB,
  product_ids          CLOB,
  excluded_product_ids CLOB,
  created_at           TIMESTAMP,
  updated_at            TIMESTAMP,
  CONSTRAINT uq_sj_search_tags_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_search_tags_active ON sj_search_tags (is_active);

-- COACH MARKS
CREATE TABLE sj_coach_marks (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id    VARCHAR2(32) NOT NULL,
  anchor_id      VARCHAR2(128),
  title          VARCHAR2(255),
  description    VARCHAR2(4000),
  screen_name    VARCHAR2(128),
  sequence_order NUMBER DEFAULT 0,
  is_active      NUMBER(1) DEFAULT 1,
  created_at     TIMESTAMP,
  updated_at     TIMESTAMP,
  CONSTRAINT uq_sj_coach_marks_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_coach_marks_anchor ON sj_coach_marks (anchor_id);

-- CATEGORY TAGS
CREATE TABLE sj_category_tags (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  name         VARCHAR2(255),
  description  VARCHAR2(4000),
  is_active    NUMBER(1) DEFAULT 1,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_category_tags_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_category_tags_name ON sj_category_tags (name);

-- DELIVERY CHARGES
CREATE TABLE sj_delivery_charges (
  id                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id             VARCHAR2(32) NOT NULL,
  location_id             NUMBER,
  pincode                 VARCHAR2(32),
  state                   VARCHAR2(128),
  city                    VARCHAR2(128),
  district                VARCHAR2(128),
  apply_default_charge    NUMBER(1) DEFAULT 0,
  charge                  NUMBER(18,2),
  min_cart_value          NUMBER(18,2),
  tiers                   CLOB,
  serviceable_for_customer NUMBER(1) DEFAULT 0,
  serviceable_for_retailer NUMBER(1) DEFAULT 0,
  serviceable_for_wholesaler NUMBER(1) DEFAULT 0,
  is_active               NUMBER(1) DEFAULT 1,
  description             VARCHAR2(4000),
  created_at              TIMESTAMP,
  updated_at              TIMESTAMP,
  CONSTRAINT uq_sj_delivery_charges_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_delivery_charges_pincode ON sj_delivery_charges (pincode);
CREATE INDEX ix_sj_delivery_charges_active ON sj_delivery_charges (is_active);

-- DELIVERY CHARGE DEFAULTS
CREATE TABLE sj_delivery_charge_defaults (
  id                       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id              VARCHAR2(32) NOT NULL,
  tiers                    CLOB,
  applicable_to_wholesaler NUMBER(1) DEFAULT 1,
  applicable_to_retailer   NUMBER(1) DEFAULT 1,
  is_active                NUMBER(1) DEFAULT 1,
  created_at               TIMESTAMP,
  updated_at               TIMESTAMP,
  CONSTRAINT uq_sj_dc_defaults_external UNIQUE (external_id)
);

-- SAVED FOR LATER
CREATE TABLE sj_saved_for_later (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  user_id      VARCHAR2(32) NOT NULL,
  product_id   VARCHAR2(32) NOT NULL,
  saved_at     TIMESTAMP,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_saved_for_later_external UNIQUE (external_id),
  CONSTRAINT uq_sfl_user_product UNIQUE (user_id, product_id)
);
CREATE INDEX ix_sj_saved_for_later_user ON sj_saved_for_later (user_id);

-- REFERRAL SETTINGS
CREATE TABLE sj_referral_settings (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id    VARCHAR2(32) NOT NULL,
  segment        VARCHAR2(32) NOT NULL,
  discount_type  VARCHAR2(32),
  discount_value NUMBER(18,2) DEFAULT 0,
  is_active      NUMBER(1) DEFAULT 0,
  created_at     TIMESTAMP,
  updated_at     TIMESTAMP,
  CONSTRAINT uq_sj_referral_settings_external UNIQUE (external_id),
  CONSTRAINT uq_sj_referral_settings_segment UNIQUE (segment)
);
CREATE INDEX ix_sj_referral_settings_segment ON sj_referral_settings (segment);

-- EVENTS
CREATE TABLE sj_events (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  event_type   VARCHAR2(64),
  payload      CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_events_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_events_created ON sj_events (created_at);
CREATE INDEX ix_sj_events_type ON sj_events (event_type);

-- CUSTOMER SEGMENTS
CREATE TABLE sj_customer_segments (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id  VARCHAR2(32) NOT NULL,
  type         VARCHAR2(64),
  payload      CLOB,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT uq_sj_customer_segments_external UNIQUE (external_id)
);
CREATE INDEX ix_sj_customer_segments_type ON sj_customer_segments (type);

-- GOOGLE REVIEWS
CREATE TABLE sj_google_reviews (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  external_id   VARCHAR2(32) NOT NULL,
  rating        NUMBER(3,2),
  review_count  VARCHAR2(32),
  last_updated  VARCHAR2(64),
  method        VARCHAR2(32),
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_sj_google_reviews_external UNIQUE (external_id)
);
